language: node_js
node_js:
  - "14"

# Caching node modules
cache:
  directories:
    - "node_modules"

# Install dependencies
install:
  - npm install

# Run tests
script:
  - npm test

# Notification settings
notifications:
  email:
    recipients:
      - ojdevit@gmail.com
    on_success: change
    on_failure: always
